// SPDX-License-Identifier: AGPL-3.0-or-later
// The migration routine: scaffold a gated job workspace, seal its reference,
// verify byte-exact, and keep the append-only verdict trail.
//
// The division of labour: migrate new generates everything except the target
// logic; a coding agent (or a human) writes that inside the skeleton; and the
// gate - the existing validator - is the only authority that lets anything
// pass. See docs/superpowers/specs/2026-09-16-migration-routine-design.md.
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

pub const LANGUAGE: &str = "rust";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InputDecl {
    pub path: String,
    pub format: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Spec {
    pub name: String,
    pub language: String,
    pub inputs: Vec<InputDecl>,
    pub outputs: Vec<String>,
    #[serde(default)]
    pub schema: serde_json::Value,
    #[serde(default)]
    pub sealed_reference_sha256: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Verdict {
    pub attempt: u64,
    pub timestamp: String,
    pub verdict: String,
    pub files_compared: Vec<String>,
    pub diffs: Vec<String>,
    pub reference_manifest: String,
    pub target_output_sha256: String,
}

pub fn spec_path(job: &Path) -> PathBuf {
    job.join("SPEC.json")
}

pub fn read_spec(job: &Path) -> Result<Spec, String> {
    let raw = fs::read_to_string(spec_path(job))
        .map_err(|e| format!("cannot read {}: {e}", spec_path(job).display()))?;
    serde_json::from_str(&raw)
        .map_err(|e| format!("{} is not a valid SPEC.json: {e}", spec_path(job).display()))
}

pub fn write_spec(job: &Path, spec: &Spec) -> Result<(), String> {
    let raw = serde_json::to_string_pretty(spec).map_err(|e| e.to_string())?;
    fs::write(spec_path(job), raw + "\n").map_err(|e| e.to_string())
}

/// The crate name for the generated target: lowercase, alphanumerics and
/// hyphens only, never empty.
pub fn crate_name(name: &str) -> Result<String, String> {
    let mut out = String::new();
    for ch in name.trim().to_lowercase().chars() {
        out.push(if ch.is_ascii_alphanumeric() { ch } else { '-' });
    }
    if out.is_empty() {
        return Err("job name is empty".into());
    }
    Ok(out)
}

fn write(path: &Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("cannot create {}: {e}", parent.display()))?;
    }
    fs::write(path, content).map_err(|e| format!("cannot write {}: {e}", path.display()))
}

fn rust_template(spec: &Spec) -> String {
    let inputs = spec
        .inputs
        .iter()
        .map(|i| format!("\"{}\"", i.path))
        .collect::<Vec<_>>()
        .join(", ");
    let outputs = spec
        .outputs
        .iter()
        .map(|o| format!("\"{}\"", o))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        r#"// Generated by `bylazora-core migrate new`. The contract:
// argv[1] = input directory, argv[2] = output directory.
// Read the declared inputs from argv[1], write the declared outputs to argv[2].
// The gate (bylazora-core migrate verify) compares your outputs against the
// sealed reference byte for byte. One differing byte is a failure with a diff.
use std::env;
use std::fs;

const INPUTS: &[&str] = &[{inputs}];
const OUTPUTS: &[&str] = &[{outputs}];

fn main() {{
    let args: Vec<String> = env::args().collect();
    let input_dir = &args[1];
    let output_dir = &args[2];
    fs::create_dir_all(output_dir).expect("output dir");

    // TODO: the logic goes here. Read INPUTS from input_dir, compute the
    // migration's outputs, write OUTPUTS to output_dir. Until then the gate
    // correctly reports MISMATCH.

    for out in OUTPUTS {{
        fs::write(format!("{{}}/{{}}", output_dir, out), "").expect("write stub");
    }}
}}
"#,
        inputs = inputs,
        outputs = outputs,
    )
}

fn cargo_template(name: &str) -> String {
    format!(
        "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[[bin]]\nname = \"{name}\"\npath = \"src/main.rs\"\n"
    )
}

fn readme_template(name: &str) -> String {
    format!(
        "# {name}: rules for whoever writes the logic\n\nThe contract is SPEC.json. The gate is absolute: only\n`bylazora-core migrate verify` (which calls the validator) marks a run\nproven. Run it often; read the diff; a MISMATCH is a diff to fix, never a\nthreshold to tune. The canon rules live in the agents/ rule pack.\n"
    )
}

fn capture_template(cobol_source: Option<&Path>, spec: &Spec) -> String {
    match cobol_source {
        None => r#"#!/usr/bin/env bash
# Generated: no capture command was configured. Place the legacy run's
# output files in output/ - or edit this script to produce them (GnuCOBOL,
# a mainframe job, anything). It must leave output/ non-empty.
set -euo pipefail
cd "$(dirname "$0")"
echo "no capture command configured: put the legacy outputs in output/" >&2
exit 2
"#
        .to_string(),
        Some(src) => {
            let inputs = spec
                .inputs
                .iter()
                .map(|i| format!("\"{}\"", i.path))
                .collect::<Vec<_>>()
                .join(" ");
            format!(
                r#"#!/usr/bin/env bash
# Generated: the reference is produced by compiling the legacy COBOL with
# GnuCOBOL and running it on the declared inputs. Edit as the job requires;
# it must leave output/ non-empty.
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p output
cobc -x -o /tmp/{name}-reference {src}
/tmp/{name}-reference {inputs}
"#,
                name = spec.name,
                src = src.display(),
                inputs = inputs,
            )
        }
    }
}

fn verify_sh_template() -> String {
    r#"#!/usr/bin/env bash
# Runs the full gate for this job: build the target, run it on the declared
# inputs, and byte-compare its outputs against the sealed reference.
set -euo pipefail
exec bylazora-core migrate verify "$(cd "$(dirname "$0")" && pwd)"
"#
    .to_string()
}

const GITIGNORE: &str = "target/rust/target\ntarget/rust/output\n";

pub fn cmd_new(
    job: &str,
    dir: Option<&Path>,
    inputs: &[String],
    outputs: &[String],
    copybook: Option<&Path>,
    cobol_source: Option<&Path>,
) -> Result<(), String> {
    if inputs.is_empty() {
        return Err("at least one --input is required".into());
    }
    if outputs.is_empty() {
        return Err("at least one --output is required".into());
    }
    let name = crate_name(job)?;
    let base = dir.unwrap_or_else(|| Path::new("."));
    let job_dir = base.join(&name);
    if job_dir.exists() {
        return Err(format!("{} already exists", job_dir.display()));
    }
    let mut spec = Spec {
        name: name.clone(),
        language: LANGUAGE.into(),
        inputs: inputs
            .iter()
            .map(|p| InputDecl {
                path: p.clone(),
                format: "csv".into(),
            })
            .collect(),
        outputs: outputs.to_vec(),
        schema: serde_json::Value::Object(Default::default()),
        sealed_reference_sha256: String::new(),
    };
    if let Some(cb) = copybook {
        let source = fs::read_to_string(cb).map_err(|e| format!("cannot read copybook: {e}"))?;
        let fields = crate::copybook::parse_copybook(&source).map_err(|e| e.to_string())?;
        spec.schema = crate::copybook::field_schema(&fields);
    }
    write(
        &job_dir.join("SPEC.json"),
        &(serde_json::to_string_pretty(&spec).map_err(|e| e.to_string())? + "\n"),
    )?;
    write(&job_dir.join("input/.keep"), "")?;
    write(
        &job_dir.join("reference/capture.sh"),
        &capture_template(cobol_source, &spec),
    )?;
    write(&job_dir.join("reference/output/.keep"), "")?;
    write(
        &job_dir.join("target/rust/Cargo.toml"),
        &cargo_template(&spec.name),
    )?;
    write(
        &job_dir.join("target/rust/src/main.rs"),
        &rust_template(&spec),
    )?;
    write(
        &job_dir.join("target/rust/README.md"),
        &readme_template(&spec.name),
    )?;
    write(&job_dir.join("target/rust/output/.keep"), "")?;
    write(&job_dir.join("verify.sh"), &verify_sh_template())?;
    write(&job_dir.join("runs/.keep"), "")?;
    write(&job_dir.join(".gitignore"), GITIGNORE)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        for f in ["reference/capture.sh", "verify.sh"] {
            let p = job_dir.join(f);
            let mut perm = fs::metadata(&p).map_err(|e| e.to_string())?.permissions();
            perm.set_mode(0o755);
            fs::set_permissions(&p, perm).map_err(|e| e.to_string())?;
        }
    }
    println!("scaffolded {} ({})", job_dir.display(), spec.name);
    println!(
        "next: seal the reference: bylazora-core migrate reference {}",
        job_dir.display()
    );
    Ok(())
}

/// Sorted file names (files only) in a directory.
pub fn file_names(dir: &Path) -> Result<Vec<String>, String> {
    let mut names: BTreeSet<String> = BTreeSet::new();
    for entry in fs::read_dir(dir).map_err(|e| format!("cannot read {}: {e}", dir.display()))? {
        let entry = entry.map_err(|e| e.to_string())?;
        if entry.file_type().map(|t| t.is_file()).unwrap_or(false) {
            if let Ok(n) = entry.file_name().into_string() {
                names.insert(n);
            }
        }
    }
    Ok(names.into_iter().collect())
}

fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(bytes);
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

/// Per-file hashes, one line each, plus an overall line whose marker is
/// .overall. The overall hash is the sha256 of the concatenated per-file
/// hashes, so it depends on both content and names.
pub fn dir_manifest(dir: &Path) -> Result<String, String> {
    let mut overall = String::new();
    let mut lines = Vec::new();
    for name in file_names(dir)? {
        let bytes = fs::read(dir.join(&name)).map_err(|e| e.to_string())?;
        let h = sha256_hex(&bytes);
        overall.push_str(&h);
        lines.push(format!("{h}  {name}"));
    }
    lines.push(format!("{}  .overall", sha256_hex(overall.as_bytes())));
    Ok(lines.join("\n") + "\n")
}

pub fn cmd_reference(job: &Path, from: Option<&Path>, force: bool) -> Result<(), String> {
    let mut spec = read_spec(job)?;
    if !spec.sealed_reference_sha256.is_empty() && !force {
        return Err("reference already sealed; use --force to replace the contract".into());
    }
    let out = job.join("reference/output");
    fs::remove_dir_all(&out).map_err(|e| e.to_string())?;
    fs::create_dir_all(&out).map_err(|e| e.to_string())?;
    if let Some(from) = from {
        for name in file_names(from)? {
            fs::copy(from.join(&name), out.join(&name)).map_err(|e| e.to_string())?;
        }
    } else {
        let status = std::process::Command::new("bash")
            .arg("capture.sh")
            .current_dir(job.join("reference"))
            .status()
            .map_err(|e| format!("cannot run capture.sh: {e}"))?;
        if !status.success() {
            return Err("capture.sh failed; fix it or pass --from".into());
        }
    }
    let names = file_names(&out)?;
    if names.is_empty() {
        return Err("reference is empty after capture; nothing to seal".into());
    }
    let manifest = dir_manifest(&out)?;
    let overall = manifest
        .lines()
        .find(|l| l.ends_with(".overall"))
        .and_then(|l| l.split_whitespace().next())
        .unwrap_or("")
        .to_string();
    fs::write(job.join("reference/manifest.sha256"), &manifest).map_err(|e| e.to_string())?;
    spec.sealed_reference_sha256 = overall;
    write_spec(job, &spec)?;
    println!("sealed reference: {} file(s)", names.len());
    Ok(())
}

fn now_string() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    format!("{secs}")
}

fn next_attempt(job: &Path) -> Result<u64, String> {
    let dir = job.join("runs");
    let mut max = 0u64;
    for entry in fs::read_dir(&dir).map_err(|e| e.to_string())? {
        let entry = entry.map_err(|e| e.to_string())?;
        let name = entry.file_name().into_string().unwrap_or_default();
        if let Some(num) = name.split('-').next().and_then(|s| s.parse::<u64>().ok()) {
            max = max.max(num);
        }
    }
    Ok(max + 1)
}

pub fn last_verdict(job: &Path) -> Result<Option<Verdict>, String> {
    let dir = job.join("runs");
    let mut best: Option<(u64, PathBuf)> = None;
    for entry in fs::read_dir(&dir).map_err(|e| e.to_string())? {
        let entry = entry.map_err(|e| e.to_string())?;
        let name = entry.file_name().into_string().unwrap_or_default();
        if let Some(num) = name.split('-').next().and_then(|s| s.parse::<u64>().ok()) {
            if best.as_ref().map(|(n, _)| num > *n).unwrap_or(true) {
                best = Some((num, entry.path()));
            }
        }
    }
    match best {
        None => Ok(None),
        Some((_, p)) => {
            let raw = fs::read_to_string(&p).map_err(|e| e.to_string())?;
            serde_json::from_str(&raw)
                .map(Some)
                .map_err(|e| e.to_string())
        }
    }
}

pub fn cmd_verify(job: &Path) -> Result<(), String> {
    let spec = read_spec(job)?;
    if spec.sealed_reference_sha256.is_empty() {
        return Err("no sealed reference: run bylazora-core migrate reference first".into());
    }
    let target = job.join("target/rust");
    let build = std::process::Command::new("cargo")
        .args(["build", "--release"])
        .current_dir(&target)
        .status()
        .map_err(|e| format!("cannot run cargo build: {e}"))?;
    if !build.success() {
        return Err("target failed to build".into());
    }
    let out = target.join("output");
    fs::remove_dir_all(&out).map_err(|e| e.to_string())?;
    fs::create_dir_all(&out).map_err(|e| e.to_string())?;
    let bin = target.join("target/release").join(&spec.name);
    let run = std::process::Command::new(&bin)
        .arg(job.join("input"))
        .arg(&out)
        .status()
        .map_err(|e| format!("cannot run the target: {e}"))?;
    if !run.success() {
        return Err("target exited non-zero".into());
    }
    let diffs = crate::validator::compare_outputs(&job.join("reference/output"), &out)
        .map_err(|e| e.to_string())?;
    let verdict = if diffs.is_empty() {
        "IDENTICAL"
    } else {
        "MISMATCH"
    };
    let mut files_compared = file_names(&job.join("reference/output"))?;
    let mut target_names = file_names(&out)?;
    files_compared.append(&mut target_names);
    files_compared.sort();
    files_compared.dedup();
    let record = Verdict {
        attempt: next_attempt(job)?,
        timestamp: now_string(),
        verdict: verdict.into(),
        files_compared,
        diffs: diffs.clone(),
        reference_manifest: fs::read_to_string(job.join("reference/manifest.sha256"))
            .map_err(|e| e.to_string())?
            .lines()
            .find(|l| l.ends_with(".overall"))
            .and_then(|l| l.split_whitespace().next())
            .unwrap_or("")
            .to_string(),
        target_output_sha256: dir_manifest(&out)?
            .lines()
            .find(|l| l.ends_with(".overall"))
            .and_then(|l| l.split_whitespace().next())
            .unwrap_or("")
            .to_string(),
    };
    let raw = serde_json::to_string_pretty(&record).map_err(|e| e.to_string())?;
    fs::write(
        job.join("runs").join(format!(
            "{:04}-{}.json",
            record.attempt,
            record.verdict.to_lowercase()
        )),
        raw + "\n",
    )
    .map_err(|e| e.to_string())?;
    if diffs.is_empty() {
        println!("IDENTICAL");
        Ok(())
    } else {
        for d in &diffs {
            eprintln!("{d}");
        }
        Err(format!("MISMATCH: {} file(s) differ", diffs.len()))
    }
}

pub fn cmd_status(job: &Path) -> Result<String, String> {
    let spec = read_spec(job)?;
    let mut out = format!(
        "job {} ({})\n  inputs : {}\n  outputs: {}\n  sealed : {}",
        spec.name,
        spec.language,
        spec.inputs
            .iter()
            .map(|i| i.path.clone())
            .collect::<Vec<_>>()
            .join(", "),
        spec.outputs.join(", "),
        if spec.sealed_reference_sha256.is_empty() {
            "no"
        } else {
            "yes"
        },
    );
    match last_verdict(job)? {
        None => out.push_str("\n  verdict: none yet"),
        Some(v) => out.push_str(&format!(
            "\n  verdict: {} (attempt {}, {} diffs)",
            v.verdict,
            v.attempt,
            v.diffs.len()
        )),
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp(name: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("bylazora-mig-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&d);
        fs::create_dir_all(&d).unwrap();
        d
    }

    fn new_workspace(dir: &Path) -> PathBuf {
        cmd_new(
            "batch-txn",
            Some(dir),
            &["transactions.csv".into()],
            &["final_balances.csv".into()],
            None,
            None,
        )
        .unwrap();
        dir.join("batch-txn")
    }

    fn make_reference(job: &Path) {
        let src = job.parent().unwrap().join("legacy");
        fs::create_dir_all(&src).unwrap();
        fs::write(src.join("final_balances.csv"), "golden\n").unwrap();
        cmd_reference(job, Some(&src), false).unwrap();
    }

    fn make_input(job: &Path) {
        fs::create_dir_all(job.join("input")).unwrap();
        fs::write(job.join("input/transactions.csv"), "a,b\n").unwrap();
    }

    /// Overwrite the target with a minimal program that writes the golden
    /// bytes, so the gate must report IDENTICAL.
    fn make_golden_target(job: &Path) {
        let main = r#"use std::env;
use std::fs;
fn main() {
    let args: Vec<String> = env::args().collect();
    let output_dir = &args[2];
    fs::create_dir_all(output_dir).expect("output dir");
    fs::write(format!("{}/final_balances.csv", output_dir), "golden\n").expect("write");
}
"#;
        fs::write(job.join("target/rust/src/main.rs"), main).unwrap();
    }

    #[test]
    fn new_scaffolds_the_full_tree() {
        let d = temp("tree");
        new_workspace(&d);
        let job = d.join("batch-txn");
        for p in [
            "SPEC.json",
            "input",
            "reference/capture.sh",
            "reference/output",
            "target/rust/Cargo.toml",
            "target/rust/src/main.rs",
            "target/rust/README.md",
            "verify.sh",
            "runs",
            ".gitignore",
        ] {
            assert!(job.join(p).exists(), "missing {p}");
        }
    }

    #[test]
    fn new_writes_the_spec_with_declared_io() {
        let d = temp("spec");
        new_workspace(&d);
        let spec = read_spec(&d.join("batch-txn")).unwrap();
        assert_eq!(spec.name, "batch-txn");
        assert_eq!(spec.language, "rust");
        assert_eq!(spec.inputs.len(), 1);
        assert_eq!(spec.inputs[0].path, "transactions.csv");
        assert_eq!(spec.inputs[0].format, "csv");
        assert_eq!(spec.outputs, vec!["final_balances.csv"]);
        assert!(spec.sealed_reference_sha256.is_empty());
    }

    #[test]
    fn new_refuses_an_existing_job() {
        let d = temp("twice");
        new_workspace(&d);
        assert!(cmd_new(
            "batch-txn",
            Some(&d),
            &["x".into()],
            &["y".into()],
            None,
            None
        )
        .is_err());
    }

    #[test]
    fn new_requires_inputs_and_outputs() {
        let d = temp("empty");
        assert!(cmd_new("j", Some(&d), &[], &["o".into()], None, None).is_err());
        assert!(cmd_new("j", Some(&d), &["i".into()], &[], None, None).is_err());
    }

    #[test]
    fn new_picks_capture_mode_from_cobol_source() {
        let d = temp("cap");
        cmd_new(
            "capjob",
            Some(&d),
            &["in.csv".into()],
            &["out.csv".into()],
            None,
            Some(Path::new("LEGACY.cob")),
        )
        .unwrap();
        let script = fs::read_to_string(d.join("capjob/reference/capture.sh")).unwrap();
        assert!(script.contains("cobc"), "gnucobol mode expected: {script}");
        let d2 = temp("manual");
        cmd_new(
            "mjob",
            Some(&d2),
            &["in.csv".into()],
            &["out.csv".into()],
            None,
            None,
        )
        .unwrap();
        let script2 = fs::read_to_string(d2.join("mjob/reference/capture.sh")).unwrap();
        assert!(
            script2.contains("exit 2"),
            "manual mode expected: {script2}"
        );
    }

    #[test]
    fn the_generated_target_compiles_and_runs_to_a_mismatch() {
        if std::env::var_os("CARGO").is_none() {
            println!("skipped: cargo is not on this host");
            return;
        }
        let d = temp("build");
        new_workspace(&d);
        let job = d.join("batch-txn");
        let status = std::process::Command::new("cargo")
            .args(["build", "--release"])
            .current_dir(job.join("target/rust"))
            .status()
            .unwrap();
        assert!(status.success());
        make_input(&job);
        let status = std::process::Command::new(job.join("target/rust/target/release/batch-txn"))
            .arg(job.join("input"))
            .arg(job.join("target/rust/output"))
            .status()
            .unwrap();
        assert!(status.success());
        assert!(job.join("target/rust/output/final_balances.csv").exists());
    }

    #[test]
    fn reference_manual_copy_seals_and_hashes() {
        let d = temp("seal");
        let job = new_workspace(&d);
        make_reference(&job);
        let spec = read_spec(&job).unwrap();
        assert!(!spec.sealed_reference_sha256.is_empty());
        assert!(job.join("reference/manifest.sha256").exists());
        assert_eq!(
            fs::read_to_string(job.join("reference/output/final_balances.csv")).unwrap(),
            "golden\n"
        );
    }

    #[test]
    fn reference_refuses_reseal_without_force() {
        let d = temp("reseal");
        let job = new_workspace(&d);
        let src = d.join("legacy");
        fs::create_dir_all(&src).unwrap();
        fs::write(src.join("final_balances.csv"), "a\n").unwrap();
        cmd_reference(&job, Some(&src), false).unwrap();
        let before = read_spec(&job).unwrap().sealed_reference_sha256;
        fs::write(src.join("final_balances.csv"), "b\n").unwrap();
        assert!(cmd_reference(&job, Some(&src), false).is_err());
        assert_eq!(read_spec(&job).unwrap().sealed_reference_sha256, before);
        cmd_reference(&job, Some(&src), true).unwrap();
        assert_ne!(read_spec(&job).unwrap().sealed_reference_sha256, before);
    }

    #[test]
    fn reference_fails_on_empty_capture() {
        let d = temp("emptycap");
        let job = new_workspace(&d);
        let empty = d.join("nothing");
        fs::create_dir_all(&empty).unwrap();
        assert!(cmd_reference(&job, Some(&empty), false).is_err());
    }

    #[test]
    fn reference_runs_capture_sh_when_no_from() {
        let d = temp("capture");
        let job = new_workspace(&d);
        let script = format!(
            "#!/usr/bin/env bash\nset -euo pipefail\nmkdir -p output\nprintf 'legacy-bytes' > output/final_balances.csv\n"
        );
        fs::write(job.join("reference/capture.sh"), script).unwrap();
        cmd_reference(&job, None, false).unwrap();
        assert_eq!(
            fs::read_to_string(job.join("reference/output/final_balances.csv")).unwrap(),
            "legacy-bytes"
        );
    }

    #[test]
    fn verify_stub_target_reports_mismatch_and_records() {
        let d = temp("vstub");
        let job = new_workspace(&d);
        make_input(&job);
        make_reference(&job);
        let err = cmd_verify(&job).unwrap_err();
        assert!(err.contains("MISMATCH"), "{err}");
        let verdict = last_verdict(&job).unwrap().unwrap();
        assert_eq!(verdict.verdict, "MISMATCH");
        assert_eq!(verdict.attempt, 1);
        assert!(
            verdict.diffs.iter().any(|d| d.contains("content differs")),
            "{:?}",
            verdict.diffs
        );
    }

    #[test]
    fn verify_reports_identical_when_the_target_matches() {
        let d = temp("vid");
        let job = new_workspace(&d);
        make_input(&job);
        make_reference(&job);
        make_golden_target(&job);
        cmd_verify(&job).unwrap();
        let verdict = last_verdict(&job).unwrap().unwrap();
        assert_eq!(verdict.verdict, "IDENTICAL");
    }

    #[test]
    fn verify_requires_a_sealed_reference() {
        let d = temp("vnoref");
        let job = new_workspace(&d);
        assert!(cmd_verify(&job).unwrap_err().contains("sealed reference"));
    }

    #[test]
    fn verify_increments_attempts_and_is_append_only() {
        let d = temp("vapp");
        let job = new_workspace(&d);
        make_input(&job);
        make_reference(&job);
        cmd_verify(&job).unwrap_err();
        cmd_verify(&job).unwrap_err();
        assert_eq!(last_verdict(&job).unwrap().unwrap().attempt, 2);
        let count = fs::read_dir(job.join("runs")).unwrap().count();
        assert_eq!(count, 3); // .keep plus two verdicts
    }

    #[test]
    fn status_reports_the_spec_and_the_last_verdict() {
        let d = temp("status");
        let job = new_workspace(&d);
        let s0 = cmd_status(&job).unwrap();
        assert!(s0.contains("batch-txn"));
        assert!(s0.contains("final_balances.csv"));
        assert!(s0.contains("none yet"));
        make_input(&job);
        make_reference(&job);
        cmd_verify(&job).unwrap_err();
        let s1 = cmd_status(&job).unwrap();
        assert!(s1.contains("MISMATCH"));
    }
}
